# PostgreSQL Database Configuration for Dev Environment (Docker)
spring.datasource.url=jdbc:postgresql://localhost:5432/restaurantdb
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driverClassName=org.postgresql.Driver

# H2 Console Configuration (Disabled for Postgres)
spring.h2.console.enabled=false

# JPA Platform
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
